Closes #4541 Nuffic Results view
akvo/akvo-rsr pull request #4570
Opened 2021-06-22 08:56 UTC by ifirmawan

## Issues

- [ ] 1) Nuffic should no longer see the new/beta results tab at all. That's Geert's request/command from yesterday.
- [ ] 2) All non-Nuffic users (so everyone BUT Akvo users) should NOT see the new Results Admin tab, as we need to properly test it.
- [ ] 3) The new Results Admin tab should be made available on rsr4 so that Nuffic can test along with us Akvo users.

- [ ] Test plan | Unit test | Integration test
- [ ] Documentation

2021-06-22 14:07 UTC, punchagan commented on akvo/rsr/spa/app/modules/project-view/project-view.jsx
> +  const showResultAdmin = shouldShowFlag(userRdr.organisations, flagOrgs.AKVO_USERS) || (getSubdomainName() === 'rsr4')
`userRdr` can be `undefined` in some cases

2021-06-22 14:19 UTC, punchagan commented on akvo/rsr/spa/app/modules/project-view/project-view.jsx
> +      if(_view === 'results' && shouldShowFlag(userRdr.organisations, flagOrgs.NUFFIC)){
This exception would only need to be on `production`, but we can make the change in a later deploy if we want to.

2021-06-22 14:30 UTC, punchagan commented on akvo/rsr/spa/app/modules/results/enumerator.jsx
> +  const filteredIndicators = indicators.filter(indicator => {
It would've been nicer to have this bug fix in a separate PR.

2021-06-22 14:35 UTC, punchagan commented on akvo/rsr/spa/app/modules/project-view/project-view.jsx
> +  const showResultAdmin = shouldShowFlag(userRdr.organisations, flagOrgs.AKVO_USERS) || (getSubdomainName() === 'rsr4')
Opening the hierarchy page for a program caused this to barf

2021-06-22 14:36 UTC, punchagan requested changes
Generally looks good to me, other than the minor comments I raised. 

Apart from that we'll also need to update the old Results view to add a link to the beta view. Currently, we only show this view for Akvo users. We need to show it to the same users who see the new results view.  But, this change can come in a separate PR, if we want to push this one out, quickly.

2021-06-23 09:54 UTC, zuhdil approved these changes

2021-06-23 10:01 UTC, merged