[#4609] nuffic reports
akvo/akvo-rsr pull request #4610
Opened 2021-08-05 01:35 UTC by zuhdil

- [ ] Test plan | Unit test | Integration test
- [ ] Documentation

Closes #4609

2021-12-13 11:10 UTC, MichaelAkvo requested changes
I probably missed something since the PR is so big, but here are a few things to change or consider.

2021-12-13 11:10 UTC, MichaelAkvo commented on akvo/rsr/dataclasses.py
> +        types[type].append(result)
Could use `dict.setdefault()` here.

2021-12-13 11:10 UTC, MichaelAkvo commented on akvo/rsr/views/py_reports/utils.py
> +    return True if targets_at == 'indicator' else False
No need for a ternary

2021-12-15 08:28 UTC, zuhdil commented on akvo/rsr/dataclasses.py
> +        return item.value
Not really, one is to get a disaggregation value of the current reporting period, and the other is to get the aggregated value of contributors (child periods) plus the current reporting period.

2021-12-15 10:37 UTC, MichaelAkvo commented on akvo/rsr/dataclasses.py
> +        return item.value
Understood. I missed the `aggregated_` on line 275.

2021-12-15 10:43 UTC, MichaelAkvo approved these changes
LGTM

2021-12-15 10:43 UTC, merged