[#4721] E2E puppeteer
akvo/akvo-rsr pull request #4722
Opened 2021-12-02 08:42 UTC by zuhdil

- [ ] Test plan | Unit test | Integration test
- [ ] Documentation

Closes #4721

2021-12-03 05:22 UTC, zuhdil commented
To run the test on your local dev environment *(it requires `node` and `npm` to install your environment)*

```sh
./scripts/devhelpers/run-e2e-local.sh
```

If you want to spawn up the browser when running the test add `--spawn` argument

```sh
./scripts/devhelpers/run-e2e-local.sh --spawn
```

2021-12-03 08:46 UTC, ifirmawan approved these changes

2021-12-07 12:22 UTC, MichaelAkvo requested changes

2021-12-07 12:22 UTC, MichaelAkvo commented on .branch_name
> +master
Was this committed by accident?

2022-02-01 12:04 UTC, MichaelAkvo requested changes
All this really needs is documentation.

2022-02-08 10:59 UTC, zuhdil commented on Dockerfile-e2e
> +    && rm -rf /var/lib/apt/lists/*
I took the Dockerfile from [documentation](https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#running-puppeteer-in-docker) then I remove some comments and change the docker user. It said that it needs to install the necessary libs to make the bundled version of Chromium that Puppeteer. I think it is running a Chromium under the hood.

2022-02-08 11:03 UTC, zuhdil commented on ci/promote-test-to-prod.sh
> +if [[ $(uname -s) == "Linux" ]] && [[ ! "${HEADLESS:-}" = false ]]; then
`HEADLESS=false` is a flag to disable the headless mode, I don't think it's correct semantically to use a value other than `false`

2022-03-21 12:31 UTC, MichaelAkvo reviewed
Just one small typo and the rest looks good to me. Also tested it on my computer (the "linux" script) and it worked.

2022-03-23 12:40 UTC, MichaelAkvo approved these changes
LGTM

2022-03-23 12:40 UTC, merged