[#5169] Block switching indicators to cumulative reporting
akvo/akvo-rsr pull request #5172
Opened 2022-12-05 03:04 UTC by zuhdil

# TODO / Done

Summarize what has been changed / what has to be done in order to finalize the PR.

 - [x] Endpoint to check if any period updates have been made on indicator
 - [x] Validate cumulative attribute update
 - [ ] Hide toggle for reporting method of indicator

# Test plan

What tests are necessary to ensure this works or doesn't break anything working

 - [x] Unit test
 - [ ] Manual test

---

Closes #5169

2022-12-13 16:08 UTC, MichaelAkvo requested changes
Minor changes required @zuhdil

2022-12-13 16:08 UTC, MichaelAkvo commented on akvo/rest/serializers/indicator.py
> +                "Switching cumulative reporting is not allowed when indicator already have updates"
```suggestion
                "Switching cumulative reporting is not allowed when the indicator already has updates"
```

2022-12-14 06:03 UTC, zuhdil commented on akvo/rsr/models/result/indicator.py
> +        return Indicator.objects.filter(pk__in=family)
Fixed

2022-12-14 07:40 UTC, zuhdil reviewed
The Frontend looks good to me.

2022-12-19 13:38 UTC, MichaelAkvo approved these changes
Small bug found, but we can merge it as it is and handle that later

2022-12-19 13:38 UTC, merged